development:
  adapter: postgresql
  encoding: unicode
  database: nyx_chapter_development
  pool: 5
  host: localhost
  username: willybuttvangelderen
  password:


# test:
#   adapter: postgresql
#   encoding: unicode
#   database: nyx_chapter_test
#   pool: 5
#   host: localhost
#   username: willybuttvangelderen
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: nyx-chapter_production
#   pool: 5
#   username: nyx-chapter
#   password:
